Repository myBuddyGuard/BuddyGuard, pull requests merged in 2024-09, with the labels that each got.

#11 [chore] #9
  .vscode/settings-desc.json
  .vscode/settings.json
  fe/.eslintrc.cjs
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/index.html
  fe/package.json
  fe/pnpm-lock.yaml
  fe/public/react.svg
  fe/public/vite.svg
  fe/src/App.css
  fe/src/App.tsx
  fe/src/index.css
  fe/src/main.tsx
  fe/src/vite-env.d.ts
  fe/tsconfig.json
  fe/tsconfig.node.json
  fe/vite.config.ts
Labels: setting, 🐸 FE

#20 [feat] 공통 컴포넌트 작업
  fe/.eslintrc.cjs
  fe/.gitignore
  fe/.prettierrc
  fe/.storybook/StorybookThemeProvider.tsx
  fe/.storybook/main.ts
  fe/.storybook/preview.tsx
  fe/index.html
  fe/package.json
  fe/pnpm-lock.yaml
  fe/public/assets/icons/calendarIcon.png
  fe/public/react.svg
  fe/public/vite.svg
  fe/src/App.css
  fe/src/App.tsx
  fe/src/components/atoms/Button.stories.tsx
  fe/src/components/atoms/Button.tsx
  fe/src/components/atoms/Checkbox.stories.tsx
  fe/src/components/atoms/Checkbox.tsx
  fe/src/components/atoms/Image.stories.tsx
  fe/src/components/atoms/Image.tsx
  fe/src/components/atoms/Input.stories.tsx
  fe/src/components/atoms/Input.tsx
  fe/src/components/atoms/Span.stories.tsx
  fe/src/components/atoms/Span.tsx
  fe/src/components/icons/CheckIcon.tsx
  fe/src/context/ThemeProvider.tsx
  fe/src/index.css
  fe/src/main.tsx
  fe/src/styles/globalStyles.ts
  fe/src/styles/theme.ts
  fe/src/types/styled-components.d.ts
  fe/tsconfig.json
Labels: feat, 🐸 FE

#22 [FEAT] responsive 레이아웃 및 라우팅
  fe/.gitignore
  fe/index.html
  fe/package.json
  fe/pnpm-lock.yaml
  fe/public/icons/favicon-96x96.png
  fe/src/App.tsx
  fe/src/components/templates/ResponsiveLayout.tsx
  fe/src/constants/textConstants.ts
  fe/src/constants/urlConstants.ts
  fe/src/main.tsx
  fe/src/routes/router.tsx
  fe/src/styles/globalStyles.ts
  fe/src/styles/resetStyles.ts
  fe/src/styles/theme.ts
Labels: feat, 🐸 FE

#29 Feature/fe basic UI
  fe/public/assets/icons/My_Buddies.png
  fe/public/assets/icons/arrow_back.png
  fe/public/assets/icons/arrow_right.png
  fe/public/assets/icons/defaultBuddy.png
  fe/public/assets/icons/kakao_login_medium_wide.png
  fe/public/assets/icons/mail.png
  fe/public/assets/icons/signout.png
  fe/public/assets/icons/telephone.png
  fe/src/components/atoms/Checkbox.tsx
  fe/src/components/atoms/Span.tsx
  fe/src/components/molecule/MenuItem.tsx
  fe/src/components/molecule/MyPageItem.tsx
  fe/src/components/molecule/NotificationItem.tsx
  fe/src/components/molecule/NotificationModal.tsx
  fe/src/components/molecule/PageTitleBar.tsx
  fe/src/components/organism/BuddyInfoBar.tsx
  fe/src/components/organism/MenuList.tsx
  fe/src/components/organism/MyPageList.tsx
  fe/src/components/organism/NotificationList.tsx
  fe/src/components/organism/UserInfoBar.tsx
  fe/src/components/pages/Home.tsx
  fe/src/components/pages/Login.tsx
  fe/src/components/pages/Menu.tsx
  fe/src/components/pages/MyPage.tsx
  fe/src/components/pages/Notification.tsx
  fe/src/routes/router.tsx
Labels: 🐸 FE, design

#31 [feat] Hospital CRUD 구현
  be/build.gradle
  be/src/main/java/buddyguard/mybuddyguard/config/SwaggerConfig.java
  be/src/main/java/buddyguard/mybuddyguard/exception/InvalidRequestException.java
  be/src/main/java/buddyguard/mybuddyguard/exception/RecordNotFoundException.java
  be/src/main/java/buddyguard/mybuddyguard/hospital/controller/HospitalRecordController.java
  be/src/main/java/buddyguard/mybuddyguard/hospital/controller/reponse/HospitalRecordResponse.java
  be/src/main/java/buddyguard/mybuddyguard/hospital/controller/request/HospitalRecordCreateRequest.java
  be/src/main/java/buddyguard/mybuddyguard/hospital/controller/request/HospitalRecordUpdateRequest.java
  be/src/main/java/buddyguard/mybuddyguard/hospital/entity/HospitalRecord.java
  be/src/main/java/buddyguard/mybuddyguard/hospital/mapper/HospitalRecordMapper.java
  be/src/main/java/buddyguard/mybuddyguard/hospital/repository/HospitalRecordRepository.java
  be/src/main/java/buddyguard/mybuddyguard/hospital/service/HospitalRecordService.java
  be/src/test/java/buddyguard/mybuddyguard/hospital/service/HospitalRecordServiceTest.java
Labels: 🖥 BE

#32 [feat] Weight CRUD 구현
  be/build.gradle
  be/src/main/java/buddyguard/mybuddyguard/weight/contoller/WeightController.java
  be/src/main/java/buddyguard/mybuddyguard/weight/contoller/request/WeightCreateRequest.java
  be/src/main/java/buddyguard/mybuddyguard/weight/contoller/request/WeightUpdateRequest.java
  be/src/main/java/buddyguard/mybuddyguard/weight/contoller/response/WeightResponse.java
  be/src/main/java/buddyguard/mybuddyguard/weight/entity/Weight.java
  be/src/main/java/buddyguard/mybuddyguard/weight/mapper/WeightMapper.java
  be/src/main/java/buddyguard/mybuddyguard/weight/repository/WeightRepository.java
  be/src/main/java/buddyguard/mybuddyguard/weight/service/WeightService.java
Labels: feat, 🖥 BE

#26 [feat] 카카오 로그인 구현
  be/build.gradle
  be/src/main/java/buddyguard/mybuddyguard/config/CorsConfig.java
  be/src/main/java/buddyguard/mybuddyguard/config/SecurityConfig.java
  be/src/main/java/buddyguard/mybuddyguard/config/SwaggerConfig.java
  be/src/main/java/buddyguard/mybuddyguard/exception/FilterException.java
  be/src/main/java/buddyguard/mybuddyguard/exception/GlobalExceptionHandler.java
  be/src/main/java/buddyguard/mybuddyguard/exception/response/FilterExceptionResponse.java
  be/src/main/java/buddyguard/mybuddyguard/jwt/controller/TokenController.java
  be/src/main/java/buddyguard/mybuddyguard/jwt/entity/RefreshToken.java
  be/src/main/java/buddyguard/mybuddyguard/jwt/filter/JwtFilter.java
  be/src/main/java/buddyguard/mybuddyguard/jwt/repository/RefreshTokenRepository.java
  be/src/main/java/buddyguard/mybuddyguard/jwt/service/TokenService.java
  be/src/main/java/buddyguard/mybuddyguard/jwt/utils/TokenType.java
  be/src/main/java/buddyguard/mybuddyguard/login/controller/request/KakaoRequest.java
  be/src/main/java/buddyguard/mybuddyguard/login/controller/request/OAuth2Request.java
  be/src/main/java/buddyguard/mybuddyguard/login/dto/CustomOAuth2User.java
  be/src/main/java/buddyguard/mybuddyguard/login/dto/UserDto.java
  be/src/main/java/buddyguard/mybuddyguard/login/entity/Users.java
  be/src/main/java/buddyguard/mybuddyguard/login/exception/CustomAuthenticationEntryPoint.java
  be/src/main/java/buddyguard/mybuddyguard/login/exception/LogoutException.java
  be/src/main/java/buddyguard/mybuddyguard/login/exception/NotAccessTokenException.java
  be/src/main/java/buddyguard/mybuddyguard/login/exception/TokenExpiredException.java
  be/src/main/java/buddyguard/mybuddyguard/login/exception/TokenNotFoundException.java
  be/src/main/java/buddyguard/mybuddyguard/login/filter/CustomLogoutFilter.java
  be/src/main/java/buddyguard/mybuddyguard/login/handler/CustomSuccessHandler.java
  be/src/main/java/buddyguard/mybuddyguard/login/repository/UserRepository.java
  be/src/main/java/buddyguard/mybuddyguard/login/service/OAuth2UserService.java
Labels: feat, 🖥 BE

#41 [feat] Pet CRUD 구현
  be/src/main/java/buddyguard/mybuddyguard/login/repository/UserRepository.java
  be/src/main/java/buddyguard/mybuddyguard/pet/contoller/PetController.java
  be/src/main/java/buddyguard/mybuddyguard/pet/contoller/request/PetRegisterRequest.java
  be/src/main/java/buddyguard/mybuddyguard/pet/contoller/request/PetUpdateInformationRequest.java
  be/src/main/java/buddyguard/mybuddyguard/pet/contoller/response/PetWithUserListResponse.java
  be/src/main/java/buddyguard/mybuddyguard/pet/entity/Pet.java
  be/src/main/java/buddyguard/mybuddyguard/pet/entity/UserPet.java
  be/src/main/java/buddyguard/mybuddyguard/pet/mapper/PetMapper.java
  be/src/main/java/buddyguard/mybuddyguard/pet/mapper/UserPetMapper.java
  be/src/main/java/buddyguard/mybuddyguard/pet/repository/PetRepository.java
  be/src/main/java/buddyguard/mybuddyguard/pet/repository/UserPetRepository.java
  be/src/main/java/buddyguard/mybuddyguard/pet/service/PetService.java
  be/src/main/java/buddyguard/mybuddyguard/pet/utils/PetType.java
  be/src/main/java/buddyguard/mybuddyguard/pet/utils/UserPetRole.java
  be/src/main/java/buddyguard/mybuddyguard/weight/exception/InvalidPetRegisterException.java
  be/src/main/java/buddyguard/mybuddyguard/weight/exception/PetNotFoundException.java
  be/src/main/java/buddyguard/mybuddyguard/weight/exception/UserInformationNotFoundException.java
  be/src/test/java/buddyguard/mybuddyguard/pet/service/PetServiceTest.java
Labels: feat, 🖥 BE
